### ISSUE TITLE
GUI locked trying to play a stream

### ISSUE THREAD

**Issue by lollo78** [nightflyer73/plugin.video.floptv#5]
Hi, I'm on LibreElec 7.95.2 with rpi3. 
If I try to play a stream with this add-on kodi GUI temporarily freezes and after one or two minutes it unlock with play failed

**Comment by nightflyer73** [comment]
Videos are broken even on floptv.tv web site. Please check and report feedback.

When upstream fix this issue, this addon should work again.

**Comment by lollo78** [comment]
I checked on flop.tv website and like you say the streams are really broken: "404 non found".
What a pity :(

**Comment by nightflyer73** [comment]
Thanks for your feedback. Closing.
